// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mcp.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<McpComponent> streamMcpUi() =>
    RustLib.instance.api.crateApiMcpStreamMcpUi();

void simulateAgentEvent({required String eventType}) =>
    RustLib.instance.api.crateApiMcpSimulateAgentEvent(eventType: eventType);

@freezed
sealed class McpComponent with _$McpComponent {
  const McpComponent._();

  const factory McpComponent.card({
    required String title,
    required String content,
  }) = McpComponent_Card;
  const factory McpComponent.button({
    required String label,
    required String actionId,
  }) = McpComponent_Button;
  const factory McpComponent.markdown({required String content}) =
      McpComponent_Markdown;
  const factory McpComponent.row({required List<McpComponent> children}) =
      McpComponent_Row;
  const factory McpComponent.column({required List<McpComponent> children}) =
      McpComponent_Column;
}
