// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void resizeTerminal({required int cols, required int rows}) =>
    RustLib.instance.api.crateApiTerminalResizeTerminal(cols: cols, rows: rows);

Stream<String> initTerminal() =>
    RustLib.instance.api.crateApiTerminalInitTerminal();

void sendTerminalInput({required String input}) =>
    RustLib.instance.api.crateApiTerminalSendTerminalInput(input: input);
