// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ServerResponse> askAgent({required String prompt}) =>
    RustLib.instance.api.crateApiSimpleAskAgent(prompt: prompt);

class ServerResponse {
  final String textResponse;
  final UiElement? uiComponent;

  const ServerResponse({required this.textResponse, this.uiComponent});

  @override
  int get hashCode => textResponse.hashCode ^ uiComponent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerResponse &&
          runtimeType == other.runtimeType &&
          textResponse == other.textResponse &&
          uiComponent == other.uiComponent;
}

class UiElement {
  final WidgetType widgetType;
  final String content;
  final String id;

  const UiElement({
    required this.widgetType,
    required this.content,
    required this.id,
  });

  @override
  int get hashCode => widgetType.hashCode ^ content.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiElement &&
          runtimeType == other.runtimeType &&
          widgetType == other.widgetType &&
          content == other.content &&
          id == other.id;
}

enum WidgetType { button, markdown, codeBlock, input, card }
